apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-demo
  template:
    metadata:
      labels:
        app: volume-demo
    spec:
      containers:
      - name: app-container
        image: nginx
        volumeMounts:
        - name: app-volume
          mountPath: /data
      volumes:
      - name: app-volume
        emptyDir: {}
